src/Entity/Cart.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Cart
{
    private $cartLines;

    public function __construct()
    {
        $this->cartLines = array();
    }

    /**
     * @return CartLine[]
     */
    public function getCartLines(): iterable
    {
        return $this->cartLines;
    }

    public function addCartLine(Product $product): self
    {
        $index = $this->getCartIndexOfProduct($product);
        if ($index == -1) {
            $cartLine = new CartLine($product);
            $this->cartLines[] = $cartLine;
        } else {
            $this->cartLines[$index]->addQuantity(1);
        }
        
        return $this;
    }

    public function getCartIndexOfProduct(Product $product): int {
        if ($this->cartLines == null) { return -1;}
        
        foreach ($this->cartLines as $key => $value) {
            if ($value->getProduct()->getId() == $product->getId())
                return $key;
        }

        return -1;
    }

    public function setCartLineQuantity(Product $product, int $quantity): int
    {
        $index = $this->getCartIndexOfProduct($product);
        if ($index != -1) {
            $this->cartLines[$index]->setQuantity($quantity);

            if ($this->cartLines[$index]->getQuantity() <= 0) {
                $this->removeCartLineOfProduct($product);
            }

            return $this->cartLines[$index]->getPrice();
        }

        return 0;
    }

    public function removeCartLineOfProduct(Product $product): self
    {
        $index = $this->getCartIndexOfProduct($product);
        if ($index != -1) {
            unset($this->cartLines[$index]);
        }

        return $this;
    }

    public function getTotalPrice(): int {
        $totalPrice = 0;

        foreach ($this->cartLines as $cartLine) {
            $totalPrice += $cartLine->getPrice();
        }

        return $totalPrice;
    }
}

src/Entity/CartLine.php
<?php

namespace App\Entity;

class CartLine
{
    private $product;
    private $quantity;

    public function __construct(Product $product)
    {
        $this->product = $product;
        $this->quantity = 1;
    }

    public function getProduct() : Product {
        return $this->product;
    }

    public function setProduct(Product $product) {
        $this->product = $product;
    }

    public function getQuantity() : int {
        return $this->quantity;
    }

    public function setQuantity(int $quantity) {
        $this->quantity = $quantity;
    }

    public function addQuantity(int $quantity) {
        $this->quantity += $quantity;
    }

    public function getPrice(): int {
        return $this->quantity * $this->product->getPrice();
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\JsonResponse;

use App\Entity\Product;
use App\Entity\Cart;
use App\Repository\ProductRepository;

class CartController extends AbstractController
{
    private $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    /**
     * @Route("/cart", name="cart")
     */
    public function index(): Response
    {
        $session = $this->requestStack->getSession();

        $cart = $session->get('cart');

        if ($cart != null && !empty($cart->getCartLines())) {
            return $this->render('cart/index.html.twig', [
                'cartLines' => $cart->getCartLines(),
                'cartPrice' => $cart->getTotalPrice(),
            ]);
        }
        
        return $this->render('cart/index.html.twig', [
            'cartLines' => null,
            'cartPrice' => 0,
        ]);
    }

    /**
     * @Route("/cart/add", name="cart_add")
     */
    public function add(Request $request, ProductRepository $productRepository): RedirectResponse
    {
        $session = $this->requestStack->getSession();

        $cart = $session->get('cart');

        if ($cart == null) {
            $cart = new Cart();
        }

        $productId = $request->query->get('productId');
        $product = $productRepository->find($productId);
        $cart->addCartLine($product);

        $session->set('cart', $cart);
        
        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/setquantity", name="cart_quantity")
     */
    public function setQuantity(Request $request, ProductRepository $productRepository)
    {
        $session = $this->requestStack->getSession();

        $cart = $session->get('cart');

        if ($cart == null) {
            return $this->redirectToRoute('cart');
        }

        $productId = $request->query->get('productId');
        $product = $productRepository->find($productId);
        $jsonData = array();
        $jsonData[] = $cart->setCartLineQuantity($product, $request->query->get('quantity'));

        $jsonData[] = $cart->getTotalPrice();

        $session->set('cart', $cart);

        return new JsonResponse($jsonData);
    }

    /**
     * @Route("/cart/remove", name="cart_remove")
     */
    public function remove(Request $request, ProductRepository $productRepository)
    {
        $session = $this->requestStack->getSession();

        $cart = $session->get('cart');

        if ($cart == null) {
            return $this->redirectToRoute('cart');
        }

        $productId = $request->query->get('productId');
        $product = $productRepository->find($productId);
        $cart->removeCartLineOfProduct($product);

        $jsonData = $cart->getTotalPrice();

        $session->set('cart', $cart);

        return new JsonResponse($jsonData);
    }

    /**
     * @Route("/cart/empty", name="cart_empty")
     */
    public function empty(): RedirectResponse
    {
        $session = $this->requestStack->getSession();

        $session->remove('cart');
        
        return $this->redirectToRoute('cart');
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartController!{% endblock %}

{% block body %}
{% if app.session.get('cart') == null or cartLines == null %}
    <a href="{{ path('product_index') }}">Add products to your cart</a>
{% else %}
    <table class="table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Product Price</th>
                <th>Quantity</th>
                <th>Total Price</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for cartLine in cartLines %}
                <tr class="cartItem" id="cartItem_{{ cartLine.product.id }}">
                    <td><a href="{{ path('product_show', {'id': cartLine.product.id}) }}">{{ cartLine.product.name }}</a></td>
                    <td>${{ cartLine.product.price }}</td>
                    <td><input type="number" id="cartItem_quantity_{{ cartLine.product.id }}" onchange="changeQuantity({{ cartLine.product.id }})" min="1" max="100" value="{{ cartLine.quantity }}"></td>
                    <td>$<span class="price">{{ cartLine.getPrice() }}</span></td>
                    <td>
                        <button onclick="remove({{ cartLine.product.id }})">Remove</button>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Total Price : $<span id="totalprice">{{ cartPrice }}</span></h3>
    <p><a id="orderbtn" href="{{ path('order_new') }}">Order</a></p>
    <p><a href="{{ path('cart_empty') }}">Empty your cart</a></p>
{% endif %}
{% endblock %}

{% block scripts %}
    <script>
        function changeQuantity(productId) {
            let input = document.getElementById("cartItem_quantity_" + productId);

            var sentData = {productId : productId, quantity : input.value };

            $.ajax({
                url: "{{ path('cart_quantity') }}",
                type: 'GET',
                data: sentData,
                dataType: 'json',
                async: true,
                
                success: function(data, status) {
                    document.getElementById("cartItem_" + productId).getElementsByClassName('price')[0].innerText = data[0];
                    document.getElementById("totalprice").innerText = data[1];
                },
                error : function(xhr, textStatus, errorThrown) {
                    alert('Request failed.');  
                }
            });
        }

        function remove(productId) {
            var sentData = {productId : productId };

            $.ajax({
                url: "{{ path('cart_remove') }}",
                type: 'GET',
                data: sentData,
                async: true,
                success: function(data, status) {
                    let element = document.getElementById("cartItem_" + productId);
                    let parentElement = element.parentNode;
                    
                    parentElement.removeChild(element);

                    if (parentElement.children.length == 0) {
                        location.reload();
                    }

                    document.getElementById("totalprice").innerText = data;
                }
            });
        }
    </script>
{% endblock %}